### ISSUE TITLE
Error when running in 4.3

### ISSUE THREAD

**Issue by OctagonalHexy** [AtlerGibby/GodotNanite#1]
When trying to run this in 4.3, an error from rd.compute_list_set_push_constant() appears due to some fixes in the rendering device code.

From what I can tell, this data is meant to align with the push constant in DepthComputeShader.glsl but due to A change recently in the error handling of rd.compute_list_set_push_constant() the way the size_bytes call is sometimes 16 when the push constants for screen resolution only take up 8, it hits this error.

I tried learning enough about RenderingDevice to fix this myself but when I set the input to just match the amount of bytes I'm inputting (8), I get A validation error saying the shader expects 16 bytes for its push constant.

I tried some guides as well as AI and it all says 2 floats = an 8 byte input, and I cant find anywhere in the code this is declared explicitly as the validation layer seems to just calculate from the shader what its push constant size should be.

I get the feeling I could fix this by trying to pad the data to 16 bytes someway, but without an understanding of why its expecting that I wouldn't get much out of that experience anyway.

This is the method that's erroring.
https://github.com/AtlerGibby/GodotNanite/blob/9c9b44bf665660de2c5a83f49f077613176ea437/Scripts/GeoStream.gd#L368

This is the pull I believe caused this change between 4.2 and 4.3.
https://github.com/godotengine/godot/commit/1ab5a4734706477b572dadc04c43c8d62f772cb6

Also, thanks for getting me into Rendering device stuff, Ive been avoiding it because there is always something else to build skills in that's not constantly changing, but I think I forgot that the features Godot implements are only made well after peeps have tested them and asked for the changes they need, hence the constant adjustments to new features.

**Comment by AtlerGibby** [comment]
So, I ended up doing what you suggested by padding the push_constant array with 2 extra floats and adding 2 extra floats in the compute shader that don't do anything. I also tested this in 4.2 and 4.3 and it should work in both. My assumption for why 16 bytes is the minimum is because 16 bytes is needed to pass a float4 or vector4. I guess Godot 4.2 let me get away with not doing this. And good luck in your Rendering Device endeavors.
